# Generated by Django 3.2 on 2021-07-19 18:29

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store_backend', '0002_auto_20210719_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='dateOfPurchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
