# Generated by Django 3.2 on 2021-07-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_backend', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='productCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(default='دسته بندی نشده', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store_backend.product'),
        ),
    ]
